### ISSUE TITLE
clcomd restart via command vs. service module

### ISSUE THREAD

**Issue by neikei** [power-devops/powerha_aix#1]
Is there any reason for restarting clcomd via "command" instead of "service"?

Current implementation via "command" module.

```yaml
    - name: Stop clcomd # noqa: no-changed-when
      ansible.builtin.command:
        cmd: stopsrc -s clcomd
      ignore_errors: true # noqa: ignore-errors
      listen: "Restart clcomd"

    - name: Wait 5 seconds...
      ansible.builtin.pause:
        seconds: 5
      listen: "Restart clcomd"

    - name: Start clcomd # noqa: no-changed-when
      ansible.builtin.command:
        cmd: startsrc -s clcomd
      listen: "Restart clcomd"
```
Source: https://github.com/power-devops/powerha_aix/blob/75075e6a9776a04cd08f34c2fe552bd10ce26a4b/examples/cluster_create.yml#L73C1-L87C31

The "service" module allows state restarted and a sleep timer between stop and start, so this can be one single step if there is no reason for splitting it into smaller steps. Ansible 2.9 had an issue with the sleep between start and stop, but this is fixed in Ansible 2.10 and newer (reference: https://github.com/ansible/ansible/issues/76877).

```yaml
    - name: "Restart clcomd"
      ansible.builtin.service:
        name: clcomd
        state: restarted
        sleep: 5
      listen: "Restart clcomd"
```
